-- QUERY 2

-- 1MB
select t1.public.supplier.s_acctbal, t1.public.supplier.s_name, t1.public.nation.n_name, ca.tpch_1.part.p_partkey, ca.tpch_1.part.p_mfgr, t1.public.supplier.s_address, t1.public.supplier.s_phone, t1.public.supplier.s_comment from ca.tpch_1.part, t1.public.supplier, ca.tpch_1.partsupp, t1.public.nation, t1.public.region where ca.tpch_1.part.p_partkey = ca.tpch_1.partsupp.ps_partkey and s_suppkey = ca.tpch_1.partsupp.ps_suppkey and ca.tpch_1.part.p_type like '%BRASS' and s_nationkey = t1.public.nation.n_nationkey and t1.public.nation.n_regionkey = t1.public.region.r_regionkey and t1.public.region.r_name = 'EUROPE' and ca.tpch_1.partsupp.ps_supplycost = ( select min(ca.tpch_1.partsupp.ps_supplycost) from ca.tpch_1.partsupp, t1.public.supplier, t1.public.nation, t1.public.region where ca.tpch_1.part.p_partkey = ca.tpch_1.partsupp.ps_partkey and t1.public.supplier.s_suppkey = ca.tpch_1.partsupp.ps_suppkey and t1.public.supplier.s_nationkey = t1.public.nation.n_nationkey and t1.public.nation.n_regionkey = t1.public.region.r_regionkey and t1.public.region.r_name = 'EUROPE' ) order by t1.public.supplier.s_acctbal desc, t1.public.nation.n_name, t1.public.supplier.s_name, ca.tpch_1.part.p_partkey LIMIT 100

-- 10MB
select t10.public.supplier.s_acctbal, t10.public.supplier.s_name, t10.public.nation.n_name, ca.tpch_10.part.p_partkey, ca.tpch_10.part.p_mfgr, t10.public.supplier.s_address, t10.public.supplier.s_phone, t10.public.supplier.s_comment from ca.tpch_10.part, t10.public.supplier, ca.tpch_10.partsupp, t10.public.nation, t10.public.region where ca.tpch_10.part.p_partkey = ca.tpch_10.partsupp.ps_partkey and s_suppkey = ca.tpch_10.partsupp.ps_suppkey and ca.tpch_10.part.p_size = 15 and ca.tpch_10.part.p_type like '%BRASS' and s_nationkey = t10.public.nation.n_nationkey and t10.public.nation.n_regionkey = t10.public.region.r_regionkey and t10.public.region.r_name = 'EUROPE' and ca.tpch_10.partsupp.ps_supplycost = ( select min(ca.tpch_10.partsupp.ps_supplycost) from ca.tpch_10.partsupp, t10.public.supplier, t10.public.nation, t10.public.region where ca.tpch_10.part.p_partkey = ca.tpch_10.partsupp.ps_partkey and t10.public.supplier.s_suppkey = ca.tpch_10.partsupp.ps_suppkey and t10.public.supplier.s_nationkey = t10.public.nation.n_nationkey and t10.public.nation.n_regionkey = t10.public.region.r_regionkey and t10.public.region.r_name = 'EUROPE' ) order by t10.public.supplier.s_acctbal desc, t10.public.nation.n_name, t10.public.supplier.s_name, ca.tpch_10.part.p_partkey LIMIT 100

-- 100MB
select t100.public.supplier.s_acctbal, t100.public.supplier.s_name, t100.public.nation.n_name, ca.tpch_100.part.p_partkey, ca.tpch_100.part.p_mfgr, t100.public.supplier.s_address, t100.public.supplier.s_phone, t100.public.supplier.s_comment from ca.tpch_100.part, t100.public.supplier, ca.tpch_100.partsupp, t100.public.nation, t100.public.region where ca.tpch_100.part.p_partkey = ca.tpch_100.partsupp.ps_partkey and s_suppkey = ca.tpch_100.partsupp.ps_suppkey and ca.tpch_100.part.p_size = 15 and ca.tpch_100.part.p_type like '%BRASS' and s_nationkey = t100.public.nation.n_nationkey and t100.public.nation.n_regionkey = t100.public.region.r_regionkey and t100.public.region.r_name = 'EUROPE' and ca.tpch_100.partsupp.ps_supplycost = ( select min(ca.tpch_100.partsupp.ps_supplycost) from ca.tpch_100.partsupp, t100.public.supplier, t100.public.nation, t100.public.region where ca.tpch_100.part.p_partkey = ca.tpch_100.partsupp.ps_partkey and t100.public.supplier.s_suppkey = ca.tpch_100.partsupp.ps_suppkey and t100.public.supplier.s_nationkey = t100.public.nation.n_nationkey and t100.public.nation.n_regionkey = t100.public.region.r_regionkey and t100.public.region.r_name = 'EUROPE' ) order by t100.public.supplier.s_acctbal desc, t100.public.nation.n_name, t100.public.supplier.s_name, ca.tpch_100.part.p_partkey LIMIT 100

-- QUERY 3

-- 1MB
select t1.public.lineitem.l_orderkey, sum(t1.public.lineitem.l_extendedprice * (1 - t1.public.lineitem.l_discount)) as revenue, ca.tpch_1.orders.o_orderdate, ca.tpch_1.orders.o_shippriority, ca.tpch_1.customer.c_mktsegment from ca.tpch_1.customer, ca.tpch_1.orders, t1.public.lineitem where ca.tpch_1.customer.c_mktsegment like 'BUILDING%' and ca.tpch_1.customer.c_custkey = ca.tpch_1.orders.o_custkey and t1.public.lineitem.l_orderkey = ca.tpch_1.orders.o_orderkey and ca.tpch_1.orders.o_orderdate < date '1995-03-15' and t1.public.lineitem.l_shipdate > date '1995-03-15' group by t1.public.lineitem.l_orderkey, ca.tpch_1.customer.c_mktsegment, ca.tpch_1.orders.o_orderdate, ca.tpch_1.orders.o_shippriority order by revenue desc, ca.tpch_1.orders.o_orderdate limit 10

-- 10MB
select t10.public.lineitem.l_orderkey, sum(t10.public.lineitem.l_extendedprice * (1 - t10.public.lineitem.l_discount)) as revenue, ca.tpch_10.orders.o_orderdate, ca.tpch_10.orders.o_shippriority, ca.tpch_10.customer.c_mktsegment from ca.tpch_10.customer, ca.tpch_10.orders, t10.public.lineitem where ca.tpch_10.customer.c_mktsegment like 'BUILDING%' and ca.tpch_10.customer.c_custkey = ca.tpch_10.orders.o_custkey and t10.public.lineitem.l_orderkey = ca.tpch_10.orders.o_orderkey and ca.tpch_10.orders.o_orderdate < date '1995-03-15' and t10.public.lineitem.l_shipdate > date '1995-03-15' group by t10.public.lineitem.l_orderkey, ca.tpch_10.customer.c_mktsegment, ca.tpch_10.orders.o_orderdate, ca.tpch_10.orders.o_shippriority order by revenue desc, ca.tpch_10.orders.o_orderdate limit 10

-- 100MB
select t100.public.lineitem.l_orderkey, sum(t100.public.lineitem.l_extendedprice * (1 - t100.public.lineitem.l_discount)) as revenue, ca.tpch_100.orders.o_orderdate, ca.tpch_100.orders.o_shippriority, ca.tpch_100.customer.c_mktsegment from ca.tpch_100.customer, ca.tpch_100.orders, t100.public.lineitem where ca.tpch_100.customer.c_mktsegment like 'BUILDING%' and ca.tpch_100.customer.c_custkey = ca.tpch_100.orders.o_custkey and t100.public.lineitem.l_orderkey = ca.tpch_100.orders.o_orderkey and ca.tpch_100.orders.o_orderdate < date '1995-03-15' and t100.public.lineitem.l_shipdate > date '1995-03-15' group by t100.public.lineitem.l_orderkey, ca.tpch_100.customer.c_mktsegment, ca.tpch_100.orders.o_orderdate, ca.tpch_100.orders.o_shippriority order by revenue desc, ca.tpch_100.orders.o_orderdate limit 10

-- QUERY 4

-- 1MB
select ca.tpch_1.orders.o_orderpriority, count(*) as order_count from ca.tpch_1.orders where ca.tpch_1.orders.o_orderdate >= date '1993-07-01' and ca.tpch_1.orders.o_orderdate < date '1993-07-01' + interval '3' month and exists ( select * from t1.public.lineitem where t1.public.lineitem.l_orderkey = ca.tpch_1.orders.o_orderkey and t1.public.lineitem.l_commitdate < t1.public.lineitem.l_receiptdate ) group by ca.tpch_1.orders.o_orderpriority order by ca.tpch_1.orders.o_orderpriority

-- 10MB
select ca.tpch_10.orders.o_orderpriority, count(*) as order_count from ca.tpch_10.orders where ca.tpch_10.orders.o_orderdate >= date '1993-07-01' and ca.tpch_10.orders.o_orderdate < date '1993-07-01' + interval '3' month and exists ( select * from t10.public.lineitem where t10.public.lineitem.l_orderkey = ca.tpch_10.orders.o_orderkey and t10.public.lineitem.l_commitdate < t10.public.lineitem.l_receiptdate ) group by ca.tpch_10.orders.o_orderpriority order by ca.tpch_10.orders.o_orderpriority

-- 100MB
select ca.tpch_100.orders.o_orderpriority, count(*) as order_count from ca.tpch_100.orders where ca.tpch_100.orders.o_orderdate >= date '1993-07-01' and ca.tpch_100.orders.o_orderdate < date '1993-07-01' + interval '3' month and exists ( select * from t100.public.lineitem where t100.public.lineitem.l_orderkey = ca.tpch_100.orders.o_orderkey and t100.public.lineitem.l_commitdate < t100.public.lineitem.l_receiptdate ) group by ca.tpch_100.orders.o_orderpriority order by ca.tpch_100.orders.o_orderpriority

-- QUERY 5

-- 1MB
select t1.public.nation.n_name, sum(t1.public.lineitem.l_extendedprice * (1 - t1.public.lineitem.l_discount)) as revenue from ca.tpch_1.customer, ca.tpch_1.orders, t1.public.lineitem, t1.public.supplier, t1.public.nation, t1.public.region where ca.tpch_1.customer.c_custkey = ca.tpch_1.orders.o_custkey and t1.public.lineitem.l_orderkey = ca.tpch_1.orders.o_orderkey and t1.public.lineitem.l_suppkey = t1.public.supplier.s_suppkey and ca.tpch_1.customer.c_nationkey = t1.public.supplier.s_nationkey and t1.public.supplier.s_nationkey = t1.public.nation.n_nationkey and t1.public.nation.n_regionkey = t1.public.region.r_regionkey and t1.public.region.r_name = 'AFRICA' and ca.tpch_1.orders.o_orderdate >= date '1994-01-01' and ca.tpch_1.orders.o_orderdate < date '1994-01-01' + interval '1' year group by t1.public.nation.n_name order by revenue desc

-- 10MB
select t10.public.nation.n_name, sum(t10.public.lineitem.l_extendedprice * (1 - t10.public.lineitem.l_discount)) as revenue from ca.tpch_10.customer, ca.tpch_10.orders, t10.public.lineitem, t10.public.supplier, t10.public.nation, t10.public.region where ca.tpch_10.customer.c_custkey = ca.tpch_10.orders.o_custkey and t10.public.lineitem.l_orderkey = ca.tpch_10.orders.o_orderkey and t10.public.lineitem.l_suppkey = t10.public.supplier.s_suppkey and ca.tpch_10.customer.c_nationkey = t10.public.supplier.s_nationkey and t10.public.supplier.s_nationkey = t10.public.nation.n_nationkey and t10.public.nation.n_regionkey = t10.public.region.r_regionkey and t10.public.region.r_name = 'ASIA' and ca.tpch_10.orders.o_orderdate >= date '1994-01-01' and ca.tpch_10.orders.o_orderdate < date '1994-01-01' + interval '1' year group by t10.public.nation.n_name order by revenue desc

-- 100MB
select t100.public.nation.n_name, sum(t100.public.lineitem.l_extendedprice * (1 - t100.public.lineitem.l_discount)) as revenue from ca.tpch_100.customer, ca.tpch_100.orders, t100.public.lineitem, t100.public.supplier, t100.public.nation, t100.public.region where ca.tpch_100.customer.c_custkey = ca.tpch_100.orders.o_custkey and t100.public.lineitem.l_orderkey = ca.tpch_100.orders.o_orderkey and t100.public.lineitem.l_suppkey = t100.public.supplier.s_suppkey and ca.tpch_100.customer.c_nationkey = t100.public.supplier.s_nationkey and t100.public.supplier.s_nationkey = t100.public.nation.n_nationkey and t100.public.nation.n_regionkey = t100.public.region.r_regionkey and t100.public.region.r_name = 'ASIA' and ca.tpch_100.orders.o_orderdate >= date '1994-01-01' and ca.tpch_100.orders.o_orderdate < date '1994-01-01' + interval '1' year group by t100.public.nation.n_name order by revenue desc

-- QUERY 6
-- 1MB
select sum(t1.public.lineitem.l_extendedprice * t1.public.lineitem.l_discount) as revenue from t1.public.lineitem where t1.public.lineitem.l_shipdate >= date '1994-01-01' and t1.public.lineitem.l_shipdate < date '1994-01-01' + interval '1' year and t1.public.lineitem.l_discount between .06 - 0.01 and .06 + 0.01 and t1.public.lineitem.l_quantity < 24

-- 10MB
select sum(t10.public.lineitem.l_extendedprice * t10.public.lineitem.l_discount) as revenue from t10.public.lineitem where t10.public.lineitem.l_shipdate >= date '1994-01-01' and t10.public.lineitem.l_shipdate < date '1994-01-01' + interval '1' year and t10.public.lineitem.l_discount between .06 - 0.01 and .06 + 0.01 and t10.public.lineitem.l_quantity < 24

-- 100MB
select sum(t100.public.lineitem.l_extendedprice * t100.public.lineitem.l_discount) as revenue from t100.public.lineitem where t100.public.lineitem.l_shipdate >= date '1994-01-01' and t100.public.lineitem.l_shipdate < date '1994-01-01' + interval '1' year and t100.public.lineitem.l_discount between .06 - 0.01 and .06 + 0.01 and t100.public.lineitem.l_quantity < 24

-- QUERY 7
-- 1MB
select supp_nation, cust_nation, l_year, sum(volume) as revenue from ( select n1.n_name as supp_nation, n2.n_name as cust_nation, extract(year from t1.public.lineitem.l_shipdate) as l_year, t1.public.lineitem.l_extendedprice * (1 - t1.public.lineitem.l_discount) as volume from t1.public.supplier, t1.public.lineitem, ca.tpch_1.orders, ca.tpch_1.customer, t1.public.nation n1, t1.public.nation n2 where t1.public.supplier.s_suppkey = t1.public.lineitem.l_suppkey and ca.tpch_1.orders.o_orderkey = t1.public.lineitem.l_orderkey and ca.tpch_1.customer.c_custkey = ca.tpch_1.orders.o_custkey and t1.public.supplier.s_nationkey = n1.n_nationkey and ca.tpch_1.customer.c_nationkey = n2.n_nationkey and n2.n_name = 'FRANCE' and ( (n1.n_name = 'FRANCE' and n2.n_name = 'UNITED KINGDOM') or (n1.n_name = 'UNITED KINGDOM' and n2.n_name = 'FRANCE') ) and t1.public.lineitem.l_shipdate between date '1995-01-01' and date '1996-12-31' ) as shipping group by supp_nation, cust_nation, l_year order by supp_nation, cust_nation, l_year

-- 10MB
select supp_nation, cust_nation, l_year, sum(volume) as revenue from ( select n1.n_name as supp_nation, n2.n_name as cust_nation, extract(year from t10.public.lineitem.l_shipdate) as l_year, t10.public.lineitem.l_extendedprice * (1 - t10.public.lineitem.l_discount) as volume from t10.public.supplier, t10.public.lineitem, ca.tpch_10.orders, ca.tpch_10.customer, t10.public.nation n1, t10.public.nation n2 where t10.public.supplier.s_suppkey = t10.public.lineitem.l_suppkey and ca.tpch_10.orders.o_orderkey = t10.public.lineitem.l_orderkey and ca.tpch_10.customer.c_custkey = ca.tpch_10.orders.o_custkey and t10.public.supplier.s_nationkey = n1.n_nationkey and ca.tpch_10.customer.c_nationkey = n2.n_nationkey and ( (n1.n_name = 'FRANCE' and n2.n_name = 'GERMANY') or (n1.n_name = 'GERMANY' and n2.n_name = 'FRANCE') ) and t10.public.lineitem.l_shipdate between date '1995-01-01' and date '1996-12-31' ) as shipping group by supp_nation, cust_nation, l_year order by supp_nation, cust_nation, l_year

-- 100MB
select supp_nation, cust_nation, l_year, sum(volume) as revenue from ( select n1.n_name as supp_nation, n2.n_name as cust_nation, extract(year from t100.public.lineitem.l_shipdate) as l_year, t100.public.lineitem.l_extendedprice * (1 - t100.public.lineitem.l_discount) as volume from t100.public.supplier, t100.public.lineitem, ca.tpch_100.orders, ca.tpch_100.customer, t100.public.nation n1, t100.public.nation n2 where t100.public.supplier.s_suppkey = t100.public.lineitem.l_suppkey and ca.tpch_100.orders.o_orderkey = t100.public.lineitem.l_orderkey and ca.tpch_100.customer.c_custkey = ca.tpch_100.orders.o_custkey and t100.public.supplier.s_nationkey = n1.n_nationkey and ca.tpch_100.customer.c_nationkey = n2.n_nationkey and ( (n1.n_name = 'FRANCE' and n2.n_name = 'GERMANY') or (n1.n_name = 'GERMANY' and n2.n_name = 'FRANCE') ) and t100.public.lineitem.l_shipdate between date '1995-01-01' and date '1996-12-31' ) as shipping group by supp_nation, cust_nation, l_year order by supp_nation, cust_nation, l_year

-- QUERY 9
-- 1MB
select nation, o_year, sum(amount) as sum_profit from ( select t1.public.nation.n_name as nation, extract(year from ca.tpch_1.orders.o_orderdate) as o_year, t1.public.lineitem.l_extendedprice * (1 - t1.public.lineitem.l_discount) - ca.tpch_1.partsupp.ps_supplycost * t1.public.lineitem.l_quantity as amount from ca.tpch_1.part, t1.public.supplier, t1.public.lineitem, ca.tpch_1.partsupp, ca.tpch_1.orders, t1.public.nation where t1.public.supplier.s_suppkey = t1.public.lineitem.l_suppkey and ca.tpch_1.partsupp.ps_suppkey = t1.public.lineitem.l_suppkey and ca.tpch_1.partsupp.ps_partkey = t1.public.lineitem.l_partkey and ca.tpch_1.part.p_partkey = t1.public.lineitem.l_partkey and ca.tpch_1.orders.o_orderkey = t1.public.lineitem.l_orderkey and t1.public.supplier.s_nationkey = t1.public.nation.n_nationkey and ca.tpch_1.part.p_name like '%green%' ) as profit group by nation, o_year order by nation, o_year desc

-- 10MB
select nation, o_year, sum(amount) as sum_profit from ( select t10.public.nation.n_name as nation, extract(year from ca.tpch_10.orders.o_orderdate) as o_year, t10.public.lineitem.l_extendedprice * (1 - t10.public.lineitem.l_discount) - ca.tpch_10.partsupp.ps_supplycost * t10.public.lineitem.l_quantity as amount from ca.tpch_10.part, t10.public.supplier, t10.public.lineitem, ca.tpch_10.partsupp, ca.tpch_10.orders, t10.public.nation where t10.public.supplier.s_suppkey = t10.public.lineitem.l_suppkey and ca.tpch_10.partsupp.ps_suppkey = t10.public.lineitem.l_suppkey and ca.tpch_10.partsupp.ps_partkey = t10.public.lineitem.l_partkey and ca.tpch_10.part.p_partkey = t10.public.lineitem.l_partkey and ca.tpch_10.orders.o_orderkey = t10.public.lineitem.l_orderkey and t10.public.supplier.s_nationkey = t10.public.nation.n_nationkey and ca.tpch_10.part.p_name like '%green%' ) as profit group by nation, o_year order by nation, o_year desc

-- 100MB
select nation, o_year, sum(amount) as sum_profit from ( select t100.public.nation.n_name as nation, extract(year from ca.tpch_100.orders.o_orderdate) as o_year, t100.public.lineitem.l_extendedprice * (1 - t100.public.lineitem.l_discount) - ca.tpch_100.partsupp.ps_supplycost * t100.public.lineitem.l_quantity as amount from ca.tpch_100.part, t100.public.supplier, t100.public.lineitem, ca.tpch_100.partsupp, ca.tpch_100.orders, t100.public.nation where t100.public.supplier.s_suppkey = t100.public.lineitem.l_suppkey and ca.tpch_100.partsupp.ps_suppkey = t100.public.lineitem.l_suppkey and ca.tpch_100.partsupp.ps_partkey = t100.public.lineitem.l_partkey and ca.tpch_100.part.p_partkey = t100.public.lineitem.l_partkey and ca.tpch_100.orders.o_orderkey = t100.public.lineitem.l_orderkey and t100.public.supplier.s_nationkey = t100.public.nation.n_nationkey and ca.tpch_100.part.p_name like '%green%' ) as profit group by nation, o_year order by nation, o_year desc

-- QUERY 10
-- 1MB
select ca.tpch_1.customer.c_custkey, ca.tpch_1.customer.c_name, sum(t1.public.lineitem.l_extendedprice * (1 - t1.public.lineitem.l_discount)) as revenue, ca.tpch_1.customer.c_acctbal, t1.public.nation.n_name, ca.tpch_1.customer.c_address, ca.tpch_1.customer.c_phone, ca.tpch_1.customer.c_comment from ca.tpch_1.customer, ca.tpch_1.orders, t1.public.lineitem, t1.public.nation where ca.tpch_1.customer.c_custkey = ca.tpch_1.orders.o_custkey and t1.public.lineitem.l_orderkey = ca.tpch_1.orders.o_orderkey and ca.tpch_1.orders.o_orderdate >= date '1993-10-01' and ca.tpch_1.orders.o_orderdate < date '1993-10-01' + interval '3' month and t1.public.lineitem.l_returnflag = 'R' and ca.tpch_1.customer.c_nationkey = t1.public.nation.n_nationkey group by ca.tpch_1.customer.c_custkey, ca.tpch_1.customer.c_name, ca.tpch_1.customer.c_acctbal, t1.public.nation.n_name, ca.tpch_1.customer.c_address, ca.tpch_1.customer.c_phone, ca.tpch_1.customer.c_comment order by revenue desc LIMIT 20

-- 10MB
select ca.tpch_10.customer.c_custkey, ca.tpch_10.customer.c_name, sum(t10.public.lineitem.l_extendedprice * (1 - t10.public.lineitem.l_discount)) as revenue, ca.tpch_10.customer.c_acctbal, t10.public.nation.n_name, ca.tpch_10.customer.c_address, ca.tpch_10.customer.c_phone, ca.tpch_10.customer.c_comment from ca.tpch_10.customer, ca.tpch_10.orders, t10.public.lineitem, t10.public.nation where ca.tpch_10.customer.c_custkey = ca.tpch_10.orders.o_custkey and t10.public.lineitem.l_orderkey = ca.tpch_10.orders.o_orderkey and ca.tpch_10.orders.o_orderdate >= date '1993-10-01' and ca.tpch_10.orders.o_orderdate < date '1993-10-01' + interval '3' month and t10.public.lineitem.l_returnflag = 'R' and ca.tpch_10.customer.c_nationkey = t10.public.nation.n_nationkey group by ca.tpch_10.customer.c_custkey, ca.tpch_10.customer.c_name, ca.tpch_10.customer.c_acctbal, t10.public.nation.n_name, ca.tpch_10.customer.c_address, ca.tpch_10.customer.c_phone, ca.tpch_10.customer.c_comment order by revenue desc LIMIT 20

-- 100MB
select ca.tpch_100.customer.c_custkey, ca.tpch_100.customer.c_name, sum(t100.public.lineitem.l_extendedprice * (1 - t100.public.lineitem.l_discount)) as revenue, ca.tpch_100.customer.c_acctbal, t100.public.nation.n_name, ca.tpch_100.customer.c_address, ca.tpch_100.customer.c_phone, ca.tpch_100.customer.c_comment from ca.tpch_100.customer, ca.tpch_100.orders, t100.public.lineitem, t100.public.nation where ca.tpch_100.customer.c_custkey = ca.tpch_100.orders.o_custkey and t100.public.lineitem.l_orderkey = ca.tpch_100.orders.o_orderkey and ca.tpch_100.orders.o_orderdate >= date '1993-10-01' and ca.tpch_100.orders.o_orderdate < date '1993-10-01' + interval '3' month and t100.public.lineitem.l_returnflag = 'R' and ca.tpch_100.customer.c_nationkey = t100.public.nation.n_nationkey group by ca.tpch_100.customer.c_custkey, ca.tpch_100.customer.c_name, ca.tpch_100.customer.c_acctbal, t100.public.nation.n_name, ca.tpch_100.customer.c_address, ca.tpch_100.customer.c_phone, ca.tpch_100.customer.c_comment order by revenue desc LIMIT 20

-- Query 13
-- 1MB
select c_count, count(*) as custdist from ( select ca.tpch_1.customer.c_custkey, count(ca.tpch_1.orders.o_orderkey) c_count from ca.tpch_1.customer left outer join ca.tpch_1.orders on ca.tpch_1.customer.c_custkey = ca.tpch_1.orders.o_custkey and ca.tpch_1.orders.o_comment not like '%special%requests%' group by ca.tpch_1.customer.c_custkey ) as c_orders group by c_count order by custdist desc, c_count desc

-- 10MB
select c_count, count(*) as custdist from ( select ca.tpch_10.customer.c_custkey, count(ca.tpch_10.orders.o_orderkey) c_count from ca.tpch_10.customer left outer join ca.tpch_10.orders on ca.tpch_10.customer.c_custkey = ca.tpch_10.orders.o_custkey and ca.tpch_10.orders.o_comment not like '%special%requests%' group by ca.tpch_10.customer.c_custkey ) as c_orders group by c_count order by custdist desc, c_count desc

-- 100MB
select c_count, count(*) as custdist from ( select ca.tpch_100.customer.c_custkey, count(ca.tpch_100.orders.o_orderkey) c_count from ca.tpch_100.customer left outer join ca.tpch_100.orders on ca.tpch_100.customer.c_custkey = ca.tpch_100.orders.o_custkey and ca.tpch_100.orders.o_comment not like '%special%requests%' group by ca.tpch_100.customer.c_custkey ) as c_orders group by c_count order by custdist desc, c_count desc

-- Query 19
-- 1MB
select sum(t1.public.lineitem.l_extendedprice* (1 - t1.public.lineitem.l_discount)) as revenue from t1.public.lineitem, ca.tpch_1.part where ( ca.tpch_1.part.p_partkey = t1.public.lineitem.l_partkey and ca.tpch_1.part.p_brand like '%Brand#12%' and ca.tpch_1.part.p_container in ('SM CASE', 'SM BOX', 'SM PACK', 'SM PKG') and t1.public.lineitem.l_quantity >= 1 and t1.public.lineitem.l_quantity <= 1 + 10 and ca.tpch_1.part.p_size between 1 and 5 and t1.public.lineitem.l_shipmode in ('AIR', 'REG AIR') and t1.public.lineitem.l_shipinstruct = 'DELIVER IN PERSON' ) or ( ca.tpch_1.part.p_partkey = t1.public.lineitem.l_partkey and ca.tpch_1.part.p_brand like '%Brand#24%' and ca.tpch_1.part.p_container in ('MED BAG', 'MED BOX', 'MED PKG', 'MED PACK') and t1.public.lineitem.l_quantity >= 10 and t1.public.lineitem.l_quantity <= 10 + 10 and ca.tpch_1.part.p_size between 1 and 10 and t1.public.lineitem.l_shipmode in ('AIR', 'REG AIR') and t1.public.lineitem.l_shipinstruct = 'DELIVER IN PERSON' ) or ( ca.tpch_1.part.p_partkey = t1.public.lineitem.l_partkey and ca.tpch_1.part.p_brand like '%Brand#33%' and ca.tpch_1.part.p_container in ('LG CASE', 'LG BOX', 'LG PACK', 'LG PKG') and t1.public.lineitem.l_quantity >= 20 and t1.public.lineitem.l_quantity <= 20 + 10 and ca.tpch_1.part.p_size between 1 and 15 and t1.public.lineitem.l_shipmode in ('AIR', 'REG AIR') and t1.public.lineitem.l_shipinstruct = 'DELIVER IN PERSON' )

-- 10MB
select sum(t10.public.lineitem.l_extendedprice* (1 - t10.public.lineitem.l_discount)) as revenue from t10.public.lineitem, ca.tpch_10.part where ( ca.tpch_10.part.p_partkey = t10.public.lineitem.l_partkey and ca.tpch_10.part.p_brand = 'Brand#12' and ca.tpch_10.part.p_container in ('SM CASE', 'SM BOX', 'SM PACK', 'SM PKG') and t10.public.lineitem.l_quantity >= 1 and t10.public.lineitem.l_quantity <= 1 + 10 and ca.tpch_10.part.p_size between 1 and 5 and t10.public.lineitem.l_shipmode in ('AIR', 'AIR REG') and t10.public.lineitem.l_shipinstruct = 'DELIVER IN PERSON' ) or ( ca.tpch_10.part.p_partkey = t10.public.lineitem.l_partkey and ca.tpch_10.part.p_brand = 'Brand#23' and ca.tpch_10.part.p_container in ('MED BAG', 'MED BOX', 'MED PKG', 'MED PACK') and t10.public.lineitem.l_quantity >= 10 and t10.public.lineitem.l_quantity <= 10 + 10 and ca.tpch_10.part.p_size between 1 and 10 and t10.public.lineitem.l_shipmode in ('AIR', 'AIR REG') and t10.public.lineitem.l_shipinstruct = 'DELIVER IN PERSON' ) or ( ca.tpch_10.part.p_partkey = t10.public.lineitem.l_partkey and ca.tpch_10.part.p_brand = 'Brand#34' and ca.tpch_10.part.p_container in ('LG CASE', 'LG BOX', 'LG PACK', 'LG PKG') and t10.public.lineitem.l_quantity >= 20 and t10.public.lineitem.l_quantity <= 20 + 10 and ca.tpch_10.part.p_size between 1 and 15 and t10.public.lineitem.l_shipmode in ('AIR', 'AIR REG') and t10.public.lineitem.l_shipinstruct = 'DELIVER IN PERSON')

-- 100MB
select sum(t100.public.lineitem.l_extendedprice* (1 - t100.public.lineitem.l_discount)) as revenue from t100.public.lineitem, ca.tpch_100.part where ( ca.tpch_100.part.p_partkey = t100.public.lineitem.l_partkey and ca.tpch_100.part.p_brand = 'Brand#12' and ca.tpch_100.part.p_container in ('SM CASE', 'SM BOX', 'SM PACK', 'SM PKG') and t100.public.lineitem.l_quantity >= 1 and t100.public.lineitem.l_quantity <= 1 + 10 and ca.tpch_100.part.p_size between 1 and 5 and t100.public.lineitem.l_shipmode in ('AIR', 'AIR REG') and t100.public.lineitem.l_shipinstruct = 'DELIVER IN PERSON' ) or ( ca.tpch_100.part.p_partkey = t100.public.lineitem.l_partkey and ca.tpch_100.part.p_brand = 'Brand#23' and ca.tpch_100.part.p_container in ('MED BAG', 'MED BOX', 'MED PKG', 'MED PACK') and t100.public.lineitem.l_quantity >= 10 and t100.public.lineitem.l_quantity <= 10 + 10 and ca.tpch_100.part.p_size between 1 and 10 and t100.public.lineitem.l_shipmode in ('AIR', 'AIR REG') and t100.public.lineitem.l_shipinstruct = 'DELIVER IN PERSON' ) or ( ca.tpch_100.part.p_partkey = t100.public.lineitem.l_partkey and ca.tpch_100.part.p_brand = 'Brand#34' and ca.tpch_100.part.p_container in ('LG CASE', 'LG BOX', 'LG PACK', 'LG PKG') and t100.public.lineitem.l_quantity >= 20 and t100.public.lineitem.l_quantity <= 20 + 10 and ca.tpch_100.part.p_size between 1 and 15 and t100.public.lineitem.l_shipmode in ('AIR', 'AIR REG') and t100.public.lineitem.l_shipinstruct = 'DELIVER IN PERSON')

-- Query 20
-- 1MB
select t1.public.supplier.s_name, t1.public.supplier.s_address, t1.public.supplier.s_suppkey from t1.public.supplier, t1.public.nation where t1.public.supplier.s_suppkey in ( select ca.tpch_1.partsupp.ps_suppkey from ca.tpch_1.partsupp where ca.tpch_1.partsupp.ps_partkey in ( select ca.tpch_1.part.p_partkey from ca.tpch_1.part where ca.tpch_1.part.p_name like 'forest%' ) and ca.tpch_1.partsupp.ps_availqty > ( select 0.5 * sum(t1.public.lineitem.l_quantity) from t1.public.lineitem where t1.public.lineitem.l_partkey = ca.tpch_1.partsupp.ps_partkey and t1.public.lineitem.l_suppkey = ca.tpch_1.partsupp.ps_suppkey and t1.public.lineitem.l_shipdate >= date '1994-01-01' and t1.public.lineitem.l_shipdate < date '1994-01-01' + interval '1' year ) ) and t1.public.supplier.s_nationkey = t1.public.nation.n_nationkey order by t1.public.supplier.s_name

-- 10MB
select t10.public.supplier.s_name, t10.public.supplier.s_address, t10.public.supplier.s_suppkey from t10.public.supplier, t10.public.nation where t10.public.supplier.s_suppkey in ( select ca.tpch_10.partsupp.ps_suppkey from ca.tpch_10.partsupp where ca.tpch_10.partsupp.ps_partkey in ( select ca.tpch_10.part.p_partkey from ca.tpch_10.part where ca.tpch_10.part.p_name like 'forest%' ) and ca.tpch_10.partsupp.ps_availqty > ( select 0.5 * sum(t10.public.lineitem.l_quantity) from t10.public.lineitem where t10.public.lineitem.l_partkey = ca.tpch_10.partsupp.ps_partkey and t10.public.lineitem.l_suppkey = ca.tpch_10.partsupp.ps_suppkey and t10.public.lineitem.l_shipdate >= date '1994-01-01' and t10.public.lineitem.l_shipdate < date '1994-01-01' + interval '1' year ) ) and t10.public.supplier.s_nationkey = t10.public.nation.n_nationkey and t10.public.nation.n_name = 'CANADA' order by t10.public.supplier.s_name

-- 100MB
select t100.public.supplier.s_name, t100.public.supplier.s_address, t100.public.supplier.s_suppkey from t100.public.supplier, t100.public.nation where t100.public.supplier.s_suppkey in ( select ca.tpch_100.partsupp.ps_suppkey from ca.tpch_100.partsupp where ca.tpch_100.partsupp.ps_partkey in ( select ca.tpch_100.part.p_partkey from ca.tpch_100.part where ca.tpch_100.part.p_name like 'forest%' ) and ca.tpch_100.partsupp.ps_availqty > ( select 0.5 * sum(t100.public.lineitem.l_quantity) from t100.public.lineitem where t100.public.lineitem.l_partkey = ca.tpch_100.partsupp.ps_partkey and t100.public.lineitem.l_suppkey = ca.tpch_100.partsupp.ps_suppkey and t100.public.lineitem.l_shipdate >= date '1994-01-01' and t100.public.lineitem.l_shipdate < date '1994-01-01' + interval '1' year ) ) and t100.public.supplier.s_nationkey = t100.public.nation.n_nationkey and t100.public.nation.n_name = 'CANADA' order by t100.public.supplier.s_name

-- SSB
-- QUERY 1.1
-- 1MB
select sum(ca.ssb_1.lineorder.lo_extendedprice * ca.ssb_1.lineorder.lo_discount) as revenue from ca.ssb_1.lineorder, s1.public.date where ca.ssb_1.lineorder.lo_orderdate = s1.public.date.d_datekey and s1.public.date.d_year = 1993 and ca.ssb_1.lineorder.lo_discount between 1 and 3 and ca.ssb_1.lineorder.lo_quantity < 25

-- 10MB
select sum(ca.ssb_10.lineorder.lo_extendedprice * ca.ssb_10.lineorder.lo_discount) as revenue from ca.ssb_10.lineorder, s10.public.date where ca.ssb_10.lineorder.lo_orderdate = s10.public.date.d_datekey and s10.public.date.d_year = 1993 and ca.ssb_10.lineorder.lo_discount between 1 and 3 and ca.ssb_10.lineorder.lo_quantity < 25

-- 100MB
select sum(ca.ssb_100.lineorder.lo_extendedprice * ca.ssb_100.lineorder.lo_discount) as revenue from ca.ssb_100.lineorder, s100.public.date where ca.ssb_100.lineorder.lo_orderdate = s100.public.date.d_datekey and s100.public.date.d_year = 1993 and ca.ssb_100.lineorder.lo_discount between 1 and 3 and ca.ssb_100.lineorder.lo_quantity < 25

-- QUERY 1.2
-- 1MB
select sum(ca.ssb_1.lineorder.lo_extendedprice * ca.ssb_1.lineorder.lo_discount) as revenue from ca.ssb_1.lineorder, s1.public.date where ca.ssb_1.lineorder.lo_orderdate = s1.public.date.d_datekey and s1.public.date.d_yearmonthnum = 199401 and ca.ssb_1.lineorder.lo_discount between 4 and 6 and ca.ssb_1.lineorder.lo_quantity between 26 and 35

-- 10MB
select sum(ca.ssb_10.lineorder.lo_extendedprice * ca.ssb_10.lineorder.lo_discount) as revenue from ca.ssb_10.lineorder, s10.public.date where ca.ssb_10.lineorder.lo_orderdate = s10.public.date.d_datekey and s10.public.date.d_yearmonthnum = 199401 and ca.ssb_10.lineorder.lo_discount between 4 and 6 and ca.ssb_10.lineorder.lo_quantity between 26 and 35

-- 100MB
select sum(ca.ssb_100.lineorder.lo_extendedprice * ca.ssb_100.lineorder.lo_discount) as revenue from ca.ssb_100.lineorder, s100.public.date where ca.ssb_100.lineorder.lo_orderdate = s100.public.date.d_datekey and s100.public.date.d_yearmonthnum = 199401 and ca.ssb_100.lineorder.lo_discount between 4 and 6 and ca.ssb_100.lineorder.lo_quantity between 26 and 35

-- QUERY 1.3
-- 1MB
select sum(ca.ssb_1.lineorder.lo_extendedprice * ca.ssb_1.lineorder.lo_discount) as revenue from ca.ssb_1.lineorder, s1.public.date where ca.ssb_1.lineorder.lo_orderdate = s1.public.date.d_datekey and s1.public.date.d_weeknuminyear = 10 and s1.public.date.d_year = 1992 and ca.ssb_1.lineorder.lo_discount between 5 and 7 and ca.ssb_1.lineorder.lo_quantity between 26 and 35

-- 10MB
select sum(ca.ssb_10.lineorder.lo_extendedprice * ca.ssb_10.lineorder.lo_discount) as revenue from ca.ssb_10.lineorder, s10.public.date where ca.ssb_10.lineorder.lo_orderdate = s10.public.date.d_datekey and s10.public.date.d_weeknuminyear = 6 and s10.public.date.d_year = 1994 and ca.ssb_10.lineorder.lo_discount between 5 and 7 and ca.ssb_10.lineorder.lo_quantity between 25 and 38

-- 100MB
select sum(ca.ssb_100.lineorder.lo_extendedprice * ca.ssb_100.lineorder.lo_discount) as revenue from ca.ssb_100.lineorder, s100.public.date where ca.ssb_100.lineorder.lo_orderdate = s100.public.date.d_datekey and s100.public.date.d_weeknuminyear = 6 and s100.public.date.d_year = 1994 and ca.ssb_100.lineorder.lo_discount between 5 and 7 and ca.ssb_100.lineorder.lo_quantity between 26 and 35

-- QUERY 2.1
-- 1MB
select sum(ca.ssb_1.lineorder.lo_revenue), s1.public.date.d_year, s1.public.part.p_brand1 from ca.ssb_1.lineorder, s1.public.date, s1.public.part, s1.public.supplier where ca.ssb_1.lineorder.lo_orderdate = s1.public.date.d_datekey and ca.ssb_1.lineorder.lo_partkey = s1.public.part.p_partkey and ca.ssb_1.lineorder.lo_suppkey = s1.public.supplier.s_suppkey and s1.public.part.p_category = 'MFGR#12' and s1.public.supplier.s_region = 'AMERICA' group by s1.public.date.d_year, s1.public.part.p_brand1 order by s1.public.date.d_year, s1.public.part.p_brand1

-- 10MB
select sum(ca.ssb_10.lineorder.lo_revenue), s10.public.date.d_year, s10.public.part.p_brand1 from ca.ssb_10.lineorder, s10.public.date, s10.public.part, s10.public.supplier where ca.ssb_10.lineorder.lo_orderdate = s10.public.date.d_datekey and ca.ssb_10.lineorder.lo_partkey = s10.public.part.p_partkey and ca.ssb_10.lineorder.lo_suppkey = s10.public.supplier.s_suppkey and s10.public.part.p_category = 'MFGR#12' and s10.public.supplier.s_region = 'AMERICA' group by s10.public.date.d_year, s10.public.part.p_brand1 order by s10.public.date.d_year, s10.public.part.p_brand1


-- 100MB
select sum(ca.ssb_100.lineorder.lo_revenue), s100.public.date.d_year, s100.public.part.p_brand1 from ca.ssb_100.lineorder, s100.public.date, s100.public.part, s100.public.supplier where ca.ssb_100.lineorder.lo_orderdate = s100.public.date.d_datekey and ca.ssb_100.lineorder.lo_partkey = s100.public.part.p_partkey and ca.ssb_100.lineorder.lo_suppkey =  s100.public.supplier.s_suppkey and s100.public.part.p_category = 'MFGR#12' and  s100.public.supplier.s_region = 'AMERICA' group by s100.public.date.d_year, s100.public.part.p_brand1 order by s100.public.date.d_year, s100.public.part.p_brand1


-- QUERY 2.2
-- 1MB
select sum(ca.ssb_1.lineorder.lo_revenue), s1.public.date.d_year, s1.public.part.p_brand1 from ca.ssb_1.lineorder, s1.public.date, s1.public.part, s1.public.supplier where ca.ssb_1.lineorder.lo_orderdate = s1.public.date.d_datekey and ca.ssb_1.lineorder.lo_partkey = s1.public.part.p_partkey and ca.ssb_1.lineorder.lo_suppkey = s1.public.supplier.s_suppkey and s1.public.part.p_brand1 between 'MFGR#2221' and 'MFGR#2228' and s1.public.supplier.s_region = 'ASIA' group by s1.public.date.d_year, s1.public.part.p_brand1 order by s1.public.date.d_year, s1.public.part.p_brand1

-- 10MB
select sum(ca.ssb_10.lineorder.lo_revenue), s10.public.date.d_year, s10.public.part.p_brand1 from ca.ssb_10.lineorder, s10.public.date, s10.public.part, s10.public.supplier where ca.ssb_10.lineorder.lo_orderdate = s10.public.date.d_datekey and ca.ssb_10.lineorder.lo_partkey = s10.public.part.p_partkey and ca.ssb_10.lineorder.lo_suppkey = s10.public.supplier.s_suppkey and s10.public.part.p_brand1 between 'MFGR#2221' and 'MFGR#2228' and s10.public.supplier.s_region = 'ASIA' group by s10.public.date.d_year, s10.public.part.p_brand1 order by s10.public.date.d_year, s10.public.part.p_brand1

-- 100MB
select sum(ca.ssb_100.lineorder.lo_revenue), s100.public.date.d_year, s100.public.part.p_brand1 from ca.ssb_100.lineorder, s100.public.date, s100.public.part, s100.public.supplier where ca.ssb_100.lineorder.lo_orderdate = s100.public.date.d_datekey and ca.ssb_100.lineorder.lo_partkey = s100.public.part.p_partkey and ca.ssb_100.lineorder.lo_suppkey =  s100.public.supplier.s_suppkey and s100.public.part.p_brand1 between 'MFGR#2221' and 'MFGR#2228' and  s100.public.supplier.s_region = 'ASIA' group by s100.public.date.d_year, s100.public.part.p_brand1 order by s100.public.date.d_year, s100.public.part.p_brand1

-- QUERY 2.3
-- 1MB
select sum(ca.ssb_1.lineorder.lo_revenue), s1.public.date.d_year, s1.public.part.p_brand1 from ca.ssb_1.lineorder, s1.public.date, s1.public.part, s1.public.supplier where ca.ssb_1.lineorder.lo_orderdate = s1.public.date.d_datekey and ca.ssb_1.lineorder.lo_partkey = s1.public.part.p_partkey and ca.ssb_1.lineorder.lo_suppkey = s1.public.supplier.s_suppkey and s1.public.part.p_brand1 = 'MFGR#2221' and s1.public.supplier.s_region = 'EUROPE' group by s1.public.date.d_year, s1.public.part.p_brand1,s1.public.supplier.s_region order by s1.public.date.d_year, s1.public.part.p_brand1

-- 10MB
select sum(ca.ssb_10.lineorder.lo_revenue), s10.public.date.d_year, s10.public.part.p_brand1 from ca.ssb_10.lineorder, s10.public.date, s10.public.part, s10.public.supplier where ca.ssb_10.lineorder.lo_orderdate = s10.public.date.d_datekey and ca.ssb_10.lineorder.lo_partkey = s10.public.part.p_partkey and ca.ssb_10.lineorder.lo_suppkey = s10.public.supplier.s_suppkey and s10.public.part.p_brand1 = 'MFGR#2221' and s10.public.supplier.s_region = 'EUROPE' group by s10.public.date.d_year, s10.public.part.p_brand1 order by s10.public.date.d_year, s10.public.part.p_brand1

-- 100MB
select sum(ca.ssb_100.lineorder.lo_revenue), s100.public.date.d_year, s100.public.part.p_brand1 from ca.ssb_100.lineorder, s100.public.date, s100.public.part, s100.public.supplier where ca.ssb_100.lineorder.lo_orderdate = s100.public.date.d_datekey and ca.ssb_100.lineorder.lo_partkey = s100.public.part.p_partkey and ca.ssb_100.lineorder.lo_suppkey =  s100.public.supplier.s_suppkey and s100.public.part.p_brand1 = 'MFGR#2221' and  s100.public.supplier.s_region = 'EUROPE' group by s100.public.date.d_year, s100.public.part.p_brand1 order by s100.public.date.d_year, s100.public.part.p_brand1

-- QUERY 3.1
-- 1MB
select s1.public.customer.c_nation, s1.public.supplier.s_nation, s1.public.date.d_year, sum(ca.ssb_1.lineorder.lo_revenue) as revenue from s1.public.customer, ca.ssb_1.lineorder, s1.public.supplier, s1.public.date where ca.ssb_1.lineorder.lo_custkey = s1.public.customer.c_custkey and ca.ssb_1.lineorder.lo_suppkey = s1.public.supplier.s_suppkey and ca.ssb_1.lineorder.lo_orderdate = s1.public.date.d_datekey and s1.public.customer.c_region = 'ASIA' and s1.public.supplier.s_region = 'ASIA' and s1.public.date.d_year >= 1992 and s1.public.date.d_year <= 1997 group by s1.public.customer.c_nation, s1.public.supplier.s_nation, s1.public.date.d_year order by s1.public.date.d_year asc, revenue desc

-- 10MB
select s10.public.customer.c_nation, s10.public.supplier.s_nation, s10.public.date.d_year, sum(ca.ssb_10.lineorder.lo_revenue) as revenue from s10.public.customer, ca.ssb_10.lineorder, s10.public.supplier, s10.public.date where ca.ssb_10.lineorder.lo_custkey = s10.public.customer.c_custkey and ca.ssb_10.lineorder.lo_suppkey = s10.public.supplier.s_suppkey and ca.ssb_10.lineorder.lo_orderdate = s10.public.date.d_datekey and s10.public.customer.c_region = 'ASIA' and s10.public.supplier.s_region = 'ASIA' and s10.public.date.d_year >= 1992 and s10.public.date.d_year <= 1997 group by s10.public.customer.c_nation, s10.public.supplier.s_nation, s10.public.date.d_year order by s10.public.date.d_year asc, revenue desc

-- 100MB
select s100.public.customer.c_nation, s100.public.supplier.s_nation, s100.public.date.d_year, sum(ca.ssb_100.lineorder.lo_revenue) as revenue from s100.public.customer, ca.ssb_100.lineorder, s100.public.supplier, s100.public.date where ca.ssb_100.lineorder.lo_custkey = s100.public.customer.c_custkey and ca.ssb_100.lineorder.lo_suppkey = s100.public.supplier.s_suppkey and ca.ssb_100.lineorder.lo_orderdate = s100.public.date.d_datekey and s100.public.customer.c_region = 'ASIA' and s100.public.supplier.s_region = 'ASIA' and s100.public.date.d_year >= 1992 and s100.public.date.d_year <= 1997 group by s100.public.customer.c_nation, s100.public.supplier.s_nation, s100.public.date.d_year order by s100.public.date.d_year asc, revenue desc

-- QUERY 3.2
-- 1MB

select s1.public.customer.c_city, s1.public.supplier.s_city, s1.public.date.d_year, sum(ca.ssb_1.lineorder.lo_revenue) as revenue from s1.public.customer, ca.ssb_1.lineorder, s1.public.supplier, s1.public.date where ca.ssb_1.lineorder.lo_custkey = s1.public.customer.c_custkey and ca.ssb_1.lineorder.lo_suppkey = s1.public.supplier.s_suppkey and ca.ssb_1.lineorder.lo_orderdate = s1.public.date.d_datekey and s1.public.customer.c_nation = 'UNITED STATES' and s1.public.supplier.s_nation = 'UNITED STATES' and s1.public.date.d_year >= 1992 and s1.public.date.d_year <= 1997 group by s1.public.customer.c_city, s1.public.supplier.s_city, s1.public.date.d_year order by s1.public.date.d_year asc, revenue desc

-- 10MB
select s10.public.customer.c_city, s10.public.supplier.s_city, s10.public.date.d_year, sum(ca.ssb_10.lineorder.lo_revenue) as revenue from s10.public.customer, ca.ssb_10.lineorder, s10.public.supplier, s10.public.date where ca.ssb_10.lineorder.lo_custkey = s10.public.customer.c_custkey and ca.ssb_10.lineorder.lo_suppkey = s10.public.supplier.s_suppkey and ca.ssb_10.lineorder.lo_orderdate = s10.public.date.d_datekey and s10.public.customer.c_nation = 'UNITED STATES' and s10.public.supplier.s_nation = 'UNITED STATES' and s10.public.date.d_year >= 1992 and s10.public.date.d_year <= 1997 group by s10.public.customer.c_city, s10.public.supplier.s_city, s10.public.date.d_year order by s10.public.date.d_year asc, revenue desc

-- 100MB
select s100.public.customer.c_city, s100.public.supplier.s_city, s100.public.date.d_year, sum(ca.ssb_100.lineorder.lo_revenue) as revenue from s100.public.customer, ca.ssb_100.lineorder, s100.public.supplier, s100.public.date where ca.ssb_100.lineorder.lo_custkey = s100.public.customer.c_custkey and ca.ssb_100.lineorder.lo_suppkey = s100.public.supplier.s_suppkey and ca.ssb_100.lineorder.lo_orderdate = s100.public.date.d_datekey and s100.public.customer.c_nation = 'UNITED STATES' and s100.public.supplier.s_nation = 'UNITED STATES' and s100.public.date.d_year >= 1992 and s100.public.date.d_year <= 1997 group by s100.public.customer.c_city, s100.public.supplier.s_city, s100.public.customer.c_nation, s100.public.supplier.s_nation, s100.public.date.d_year order by s100.public.date.d_year asc, revenue desc

-- QUERY 3.3
-- 1MB
select s1.public.customer.c_city, s1.public.supplier.s_city, s1.public.date.d_year, sum(ca.ssb_1.lineorder.lo_revenue) as revenue from s1.public.customer, ca.ssb_1.lineorder, s1.public.supplier, s1.public.date where ca.ssb_1.lineorder.lo_custkey = s1.public.customer.c_custkey and ca.ssb_1.lineorder.lo_suppkey = s1.public.supplier.s_suppkey and ca.ssb_1.lineorder.lo_orderdate = s1.public.date.d_datekey and (s1.public.customer.c_city = 'UNITED KI1' or s1.public.customer.c_city = 'UNITED KI5') and (s1.public.supplier.s_city = 'UNITED KI1' or s1.public.supplier.s_city = 'UNITED KI5') and s1.public.date.d_year >= 1992 and s1.public.date.d_year <= 1997 group by s1.public.customer.c_city, s1.public.supplier.s_city, s1.public.date.d_year order by s1.public.date.d_year asc, revenue desc

-- 10MB
select s10.public.customer.c_city, s10.public.supplier.s_city, s10.public.date.d_year, sum(ca.ssb_10.lineorder.lo_revenue) as revenue from s10.public.customer, ca.ssb_10.lineorder, s10.public.supplier, s10.public.date where ca.ssb_10.lineorder.lo_custkey = s10.public.customer.c_custkey and ca.ssb_10.lineorder.lo_suppkey = s10.public.supplier.s_suppkey and ca.ssb_10.lineorder.lo_orderdate = s10.public.date.d_datekey and (s10.public.customer.c_city = 'UNITED KI1' or s10.public.customer.c_city = 'UNITED KI5') and (s10.public.supplier.s_city = 'UNITED KI1' or s10.public.supplier.s_city = 'UNITED KI5') and s10.public.date.d_year >= 1992 and s10.public.date.d_year <= 1997 group by s10.public.customer.c_city, s10.public.supplier.s_city, s10.public.date.d_year order by s10.public.date.d_year asc, revenue desc

-- 100MB
select s100.public.customer.c_city, s100.public.supplier.s_city, s100.public.date.d_year, sum(ca.ssb_100.lineorder.lo_revenue) as revenue from s100.public.customer, ca.ssb_100.lineorder, s100.public.supplier, s100.public.date where ca.ssb_100.lineorder.lo_custkey = s100.public.customer.c_custkey and ca.ssb_100.lineorder.lo_suppkey = s100.public.supplier.s_suppkey and ca.ssb_100.lineorder.lo_orderdate = s100.public.date.d_datekey and (s100.public.customer.c_city = 'UNITED KI1' or s100.public.customer.c_city = 'UNITED KI5') and (s100.public.supplier.s_city = 'UNITED KI1' or s100.public.supplier.s_city = 'UNITED KI5') and s100.public.date.d_year >= 1992 and s100.public.date.d_year <= 1997 group by s100.public.customer.c_city, s100.public.supplier.s_city, s100.public.customer.c_nation, s100.public.supplier.s_nation, s100.public.date.d_year order by s100.public.date.d_year asc, revenue desc

-- QUERY 3.4
-- 1MB
select s1.public.customer.c_city, s1.public.supplier.s_nation, s1.public.date.d_year, sum(ca.ssb_1.lineorder.lo_revenue) as revenue from s1.public.customer, ca.ssb_1.lineorder, s1.public.supplier, s1.public.date where ca.ssb_1.lineorder.lo_custkey = s1.public.customer.c_custkey and ca.ssb_1.lineorder.lo_suppkey = s1.public.supplier.s_suppkey and ca.ssb_1.lineorder.lo_orderdate = s1.public.date.d_datekey and (s1.public.customer.c_city = 'UNITED KI1' or s1.public.customer.c_city = 'UNITED KI5') and (s1.public.customer.c_city = 'UNITED KI1' or s1.public.customer.c_city = 'UNITED KI5') and s1.public.date.d_yearmonth = 'Dec1997' group by s1.public.customer.c_nation, s1.public.supplier.s_nation, s1.public.date.d_year order by s1.public.date.d_year asc, revenue desc

-- 10MB
select s10.public.customer.c_city, s10.public.supplier.s_city, s10.public.date.d_year, sum(ca.ssb_10.lineorder.lo_revenue) as revenue from s10.public.customer, ca.ssb_10.lineorder, s10.public.supplier, s10.public.date where ca.ssb_10.lineorder.lo_custkey = s10.public.customer.c_custkey and ca.ssb_10.lineorder.lo_suppkey = s10.public.supplier.s_suppkey and ca.ssb_10.lineorder.lo_orderdate = s10.public.date.d_datekey and (s10.public.customer.c_city = 'UNITED KI1' or s10.public.customer.c_city = 'UNITED KI5') and (s10.public.supplier.s_city = 'UNITED KI1' or s10.public.supplier.s_city = 'UNITED KI5') and s10.public.date.d_yearmonth = 'Dec1997' group by s10.public.customer.c_city, s10.public.supplier.s_city, s10.public.date.d_year order by s10.public.date.d_year asc, revenue desc

-- 100MB
select s100.public.customer.c_city, s100.public.supplier.s_city, s100.public.date.d_yearmonth, s100.public.date.d_year, sum(ca.ssb_100.lineorder.lo_revenue) as revenue from s100.public.customer, ca.ssb_100.lineorder, s100.public.supplier, s100.public.date where ca.ssb_100.lineorder.lo_custkey = s100.public.customer.c_custkey and ca.ssb_100.lineorder.lo_suppkey = s100.public.supplier.s_suppkey and ca.ssb_100.lineorder.lo_orderdate = s100.public.date.d_datekey and (s100.public.customer.c_city = 'UNITED KI1' or s100.public.customer.c_city = 'UNITED KI5') and (s100.public.supplier.s_city = 'UNITED KI1' or s100.public.supplier.s_city = 'UNITED KI5') and s100.public.date.d_yearmonth = 'Dec1997' group by s100.public.customer.c_city, s100.public.supplier.s_city, s100.public.date.d_yearmonth, s100.public.date.d_year order by s100.public.date.d_year asc, revenue desc;

-- QUERY 4.1

-- 1MB
select s1.public.date.d_year, s1.public.customer.c_nation, sum(ca.ssb_1.lineorder.lo_revenue - ca.ssb_1.lineorder.lo_supplycost) as profit from s1.public.date, s1.public.customer, s1.public.supplier, s1.public.part, ca.ssb_1.lineorder where ca.ssb_1.lineorder.lo_custkey = s1.public.customer.c_custkey and ca.ssb_1.lineorder.lo_suppkey = s1.public.supplier.s_suppkey and ca.ssb_1.lineorder.lo_partkey = s1.public.part.p_partkey and ca.ssb_1.lineorder.lo_orderdate = s1.public.date.d_datekey and s1.public.customer.c_region = 'AMERICA' and s1.public.supplier.s_region = 'AMERICA' and (s1.public.part.p_mfgr = 'MFGR#1' or s1.public.part.p_mfgr = 'MFGR#2') group by s1.public.date.d_year, s1.public.customer.c_nation order by s1.public.date.d_year, s1.public.customer.c_nation

-- 10MB
select s10.public.date.d_year, s10.public.customer.c_nation, sum(ca.ssb_10.lineorder.lo_revenue - ca.ssb_10.lineorder.lo_supplycost) as profit from s10.public.date, s10.public.customer, s10.public.supplier, s10.public.part, ca.ssb_10.lineorder where ca.ssb_10.lineorder.lo_custkey = s10.public.customer.c_custkey and ca.ssb_10.lineorder.lo_suppkey = s10.public.supplier.s_suppkey and ca.ssb_10.lineorder.lo_partkey = s10.public.part.p_partkey and ca.ssb_10.lineorder.lo_orderdate = s10.public.date.d_datekey and s10.public.customer.c_region = 'AMERICA' and s10.public.supplier.s_region = 'AMERICA' and (s10.public.part.p_mfgr = 'MFGR#1' or s10.public.part.p_mfgr = 'MFGR#2') group by s10.public.date.d_year, s10.public.customer.c_nation order by s10.public.date.d_year, s10.public.customer.c_nation

-- 100MB
select s100.public.date.d_year, s100.public.customer.c_nation, sum(ca.ssb_100.lineorder.lo_revenue - ca.ssb_100.lineorder.lo_supplycost) as profit from s100.public.date, s100.public.customer, s100.public.supplier, s100.public.part, ca.ssb_100.lineorder where ca.ssb_100.lineorder.lo_custkey = s100.public.customer.c_custkey and ca.ssb_100.lineorder.lo_suppkey = s100.public.supplier.s_suppkey and ca.ssb_100.lineorder.lo_partkey = s100.public.part.p_partkey and ca.ssb_100.lineorder.lo_orderdate = s100.public.date.d_datekey and s100.public.customer.c_region = 'AMERICA' and s100.public.supplier.s_region = 'AMERICA' and (s100.public.part.p_mfgr = 'MFGR#1' or s100.public.part.p_mfgr = 'MFGR#2') group by s100.public.date.d_year, s100.public.customer.c_nation order by s100.public.date.d_year, s100.public.customer.c_nation

-- QUERY 4.2
-- 1MB
select s1.public.date.d_year, s1.public.customer.c_nation, sum(ca.ssb_1.lineorder.lo_revenue - ca.ssb_1.lineorder.lo_supplycost) as profit from s1.public.date, s1.public.customer, s1.public.supplier, s1.public.part, ca.ssb_1.lineorder where ca.ssb_1.lineorder.lo_custkey = s1.public.customer.c_custkey and ca.ssb_1.lineorder.lo_suppkey = s1.public.supplier.s_suppkey and ca.ssb_1.lineorder.lo_partkey = s1.public.part.p_partkey and ca.ssb_1.lineorder.lo_orderdate = s1.public.date.d_datekey and s1.public.customer.c_region = 'AMERICA' and s1.public.supplier.s_region = 'AMERICA' and (s1.public.date.d_year = 1997 or s1.public.date.d_year = 1998) and (s1.public.part.p_mfgr = 'MFGR#1' or s1.public.part.p_mfgr = 'MFGR#2') group by s1.public.date.d_year, s1.public.customer.c_nation order by s1.public.date.d_year, s1.public.customer.c_nation

-- 10MB
select s10.public.date.d_year, s10.public.customer.c_nation, sum(ca.ssb_10.lineorder.lo_revenue - ca.ssb_10.lineorder.lo_supplycost) as profit from s10.public.date, s10.public.customer, s10.public.supplier, s10.public.part, ca.ssb_10.lineorder where ca.ssb_10.lineorder.lo_custkey = s10.public.customer.c_custkey and ca.ssb_10.lineorder.lo_suppkey = s10.public.supplier.s_suppkey and ca.ssb_10.lineorder.lo_partkey = s10.public.part.p_partkey and ca.ssb_10.lineorder.lo_orderdate = s10.public.date.d_datekey and s10.public.customer.c_region = 'AMERICA' and s10.public.supplier.s_region = 'AMERICA' and (s10.public.date.d_year = 1997 or s10.public.date.d_year = 1998) and (s10.public.part.p_mfgr = 'MFGR#1' or s10.public.part.p_mfgr = 'MFGR#2') group by s10.public.date.d_year, s10.public.customer.c_nation order by s10.public.date.d_year, s10.public.customer.c_nation

-- 100MB
select s100.public.date.d_year, s100.public.customer.c_nation, sum(ca.ssb_100.lineorder.lo_revenue - ca.ssb_100.lineorder.lo_supplycost) as profit from s100.public.date, s100.public.customer, s100.public.supplier, s100.public.part, ca.ssb_100.lineorder where ca.ssb_100.lineorder.lo_custkey = s100.public.customer.c_custkey and ca.ssb_100.lineorder.lo_suppkey = s100.public.supplier.s_suppkey and ca.ssb_100.lineorder.lo_partkey = s100.public.part.p_partkey and ca.ssb_100.lineorder.lo_orderdate = s100.public.date.d_datekey and s100.public.customer.c_region = 'AMERICA' and s100.public.supplier.s_region = 'AMERICA' and (s100.public.date.d_year = 1997 or s100.public.date.d_year = 1998) and (s100.public.part.p_mfgr = 'MFGR#1' or s100.public.part.p_mfgr = 'MFGR#2') group by s100.public.date.d_year, s100.public.customer.c_nation order by s100.public.date.d_year, s100.public.customer.c_nation

-- QUERY 4.3
-- 1MB
select s1.public.date.d_year, s1.public.customer.c_nation, sum(ca.ssb_1.lineorder.lo_revenue - ca.ssb_1.lineorder.lo_supplycost) as profit from s1.public.date, s1.public.customer, s1.public.supplier, s1.public.part, ca.ssb_1.lineorder where ca.ssb_1.lineorder.lo_custkey = s1.public.customer.c_custkey and ca.ssb_1.lineorder.lo_suppkey = s1.public.supplier.s_suppkey and ca.ssb_1.lineorder.lo_partkey = s1.public.part.p_partkey and ca.ssb_1.lineorder.lo_orderdate = s1.public.date.d_datekey and s1.public.customer.c_region = 'AMERICA' and s1.public.supplier.s_nation = 'UNITED STATES' and (s1.public.date.d_year = 1997 or s1.public.date.d_year = 1998) and s1.public.part.p_mfgr = 'MFGR#4' group by s1.public.date.d_year, s1.public.customer.c_nation order by s1.public.date.d_year, s1.public.customer.c_nation

-- 10MB
select s10.public.date.d_year, s10.public.customer.c_nation, sum(ca.ssb_10.lineorder.lo_revenue - ca.ssb_10.lineorder.lo_supplycost) as profit from s10.public.date, s10.public.customer, s10.public.supplier, s10.public.part, ca.ssb_10.lineorder where ca.ssb_10.lineorder.lo_custkey = s10.public.customer.c_custkey and ca.ssb_10.lineorder.lo_suppkey = s10.public.supplier.s_suppkey and ca.ssb_10.lineorder.lo_partkey = s10.public.part.p_partkey and ca.ssb_10.lineorder.lo_orderdate = s10.public.date.d_datekey and s10.public.customer.c_region = 'AMERICA' and s10.public.supplier.s_nation = 'UNITED STATES' and (s10.public.date.d_year = 1997 or s10.public.date.d_year = 1998) and s10.public.part.p_mfgr = 'MFGR#4' group by s10.public.date.d_year, s10.public.customer.c_nation order by s10.public.date.d_year, s10.public.customer.c_nation

-- 100MB
select s100.public.date.d_year, s100.public.customer.c_nation, sum(ca.ssb_100.lineorder.lo_revenue - ca.ssb_100.lineorder.lo_supplycost) as profit from s100.public.date, s100.public.customer, s100.public.supplier, s100.public.part, ca.ssb_100.lineorder where ca.ssb_100.lineorder.lo_custkey = s100.public.customer.c_custkey and ca.ssb_100.lineorder.lo_suppkey = s100.public.supplier.s_suppkey and ca.ssb_100.lineorder.lo_partkey = s100.public.part.p_partkey and ca.ssb_100.lineorder.lo_orderdate = s100.public.date.d_datekey and s100.public.customer.c_region = 'AMERICA' and s100.public.supplier.s_nation = 'UNITED STATES' and (s100.public.date.d_year = 1997 or s100.public.date.d_year = 1998) and s100.public.part.p_mfgr = 'MFGR#4' group by s100.public.date.d_year, s100.public.customer.c_nation order by s100.public.date.d_year, s100.public.customer.c_nation